# Generated by Django 3.2.9 on 2021-11-09 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0005_auto_20211109_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_rating',
        ),
        migrations.AddField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookMng.book'),
        ),
    ]
