# Generated by Django 3.2.9 on 2021-11-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0005_auto_20211108_1904'),
        ('bookMng', '0008_auto_20211110_0012'),
    ]

    operations = [
    ]
