# Generated by Django 3.2.9 on 2021-11-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0009_merge_0005_auto_20211108_1904_0008_auto_20211110_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='times_rated',
        ),
    ]
