# Generated by Django 3.2.9 on 2021-11-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0010_auto_20211110_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_rating',
            new_name='avg_rating',
        ),
    ]
